[package]
name = "term_dump"
version = "0.1.0"
authors = ["Alexander Dimitrov <anchorite@localhost>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unibilium = { path = "../unibilium" }
clap = "~2"
